name: Genera PDF al push su main

on:
  push:
    branches:
      - main
      
permissions:
  contents: write

jobs:
  build-and-commit-pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repository
        uses: actions/checkout@v3

      - name: Installazione completa di TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y texlive-full latexmk rsync

      - name: Compilazione del file LaTeX in PDF
        run: |
          mkdir -p pdf_output
          rsync -a --include '*/' --exclude '*' chapters/ pdf_output/chapters/
          latexmk -pdf -output-directory=pdf_output -f main.tex

      - name: Configurazione di Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Commit e push del PDF generato
        run: |
          git add pdf_output/main.pdf
          git commit -m "Aggiornamento automatico del PDF dopo il push su main" || echo "Nessuna modifica da committare"
          git push
